---

driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0011
        - ANSIBLE0010
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
